import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Nav from "@/components/layout/Nav";
import Footer from "@/components/layout/Footer";
import { SessionProvider } from "next-auth/react";
import Provider from "@/components/Provider";
import { createClient } from "@/prismicio";
import { getCategoriesAndSub } from "@/utils/queryHelper";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
    title: "Digital Gadgets",
    description: "Generated by create next app",
};

export default async function RootLayout({
    children,
}: {
    children: React.ReactNode;
}) {
    const client = createClient();
    const categories = await getCategoriesAndSub(client);

    return (
        <html lang='en'>
            <body className={inter.className}>
                <Provider>
                    <Nav categories={categories} />
                    {children}
                    <Footer />
                </Provider>
            </body>
        </html>
    );
}
